### ISSUE TITLE
Apache mongodb not loaded in plugin

### ISSUE THREAD

**Issue by cfalba80** [kulya/jmeter-gradle-plugin#59]
Hello,

I am using latest jmeter gradle plugin version 1.3.4-2.13, but when i try to run a jmeter test i am getting this error in the jmeter.log file:
2015/07/17 16:49:11 ERROR - jmeter.JMeter: Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'D:\GAP_repository\planning-service\receipt-service\src\test\Load&ReviewReceipts.jmx', conversion error com.thoughtworks.xstream.converters.ConversionException: org.apache.jmeter.protocol.mongodb.config.MongoSourceElement : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
---- Debugging information ----
message             : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
class               : org.apache.jorphan.collections.ListedHashTree
required-type       : org.apache.jorphan.collections.ListedHashTree
converter-type      : org.apache.jmeter.save.converters.HashTreeConverter
path                : /jmeterTestPlan/hashTree/hashTree/MongoSourceElement

It is like the apache mongodb component is not loaded,

this is my build.gradle file:

buildscript {

```
repositories {
    maven { url 'http://artifactory.gapinc.dev/artifactory/remote-repos' }    
    ivy {
        layout 'maven'
        url 'http://artifactory.gapinc.dev/artifactory/remote-repos'
    }
    mavenCentral()

}

dependencies {
    classpath 'com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13'
}
```

}

apply plugin: 'jmeter'

jmeterEditor.configure {
    maxHeapSize = "1200M"
}
jmeterRun.configure {
      jmeterTestFiles = [file("src/test/Load&ReviewReceipts.jmx")]
    jmeterPropertyFile = file("src/test/jmeter.properties")

}

Please take a look at this, any help will be appreciated.

Thanks

**Comment by foragerr** [comment]
Hi, the dev here seems inactive, I created a fork of this project here: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin

Can you try with that plugin as well please? I imagine the problem would still exist, but if you can verify, I will take a look into this.

**Comment by cfalba80** [comment]
It still doesn't work. Do you have any advice on this?

Thanks

**Comment by foragerr** [comment]
Continuing this conversation here: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/13

**Comment by cfalba80** [comment]
Hello,

this is the url of the project: https://github.com/cfalba80/TestJmeter

Thanks.
