### ISSUE TITLE
Running jmeter in non gui mode

### ISSUE THREAD

**Issue by ssuummit** [kulya/jmeter-gradle-plugin#60]
Hi,

I want to run Jmeter in non gui mode. In default jmeter we have -n option to run in non gui mode.
How can we achieve the same in this gradle jmeter plugin as we can not pass -n to gradle jmeterRun command?

**Comment by foragerr** [comment]
Running `jmeterRun` with this plugin always runs jmeter with `-n` enabled. You can use `jmeterEditor` to launch GUI, but that is meant to be used only to edit tests. 

BTW, I maintain a newer version of this plugin over at https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin

**Comment by ssuummit** [comment]
Hey,
Thanks a lot for helping me. I'll check the newer version.

**Comment by foragerr** [comment]
If your question is answered, you should close this issue.
