### ISSUE TITLE
Does not work if I have tomcat gradle plugin in the build file

### ISSUE THREAD

**Issue by anujkumar04** [kulya/jmeter-gradle-plugin#63]
The tomcat dependencies are not resolved. below is the build file:

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-tomcat-plugin:2.2.4'
        classpath ('com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13') {
          exclude group: 'servletapi'
          exclude group: 'org.bouncycastle'
        }
    }

}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'com.bmuschko.tomcat'
apply plugin: 'jmeter'

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

def tomcatVersion = '7.0.54'

repositories {
    mavenLocal()
    maven { url ' http://oss.jfrog.org/artifactory/libs-release/' }
}

dependencies {

```
testCompile 'junit:junit:4.12'
providedCompile "javax.servlet:javax.servlet-api:3.0.1"

tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"
tomcat "org.apache.tomcat.embed:tomcat-embed-logging-log4j:${tomcatVersion}"
tomcat("org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}") {
}
```

}

jmeterRun.configure {  
  jmeterTestFiles = [ file("src/test/jmeter/Test.jmx") ]
  jmeterPropertyFile = file("src/test/jmeter/jmeter.properties")
  jmeterUserProperties = ["SERVER="+System.getProperty('SERVER',"localhost"),"PORT="+System.getProperty('PORT',"8080")]
}

And I am getting the below error:

Could not resolve all dependencies for configuration ':tomcat'.

> Could not find org.apache.tomcat.embed:tomcat-embed-core:7.0.54.

**Comment by foragerr** [comment]
Hi, this project has been dormant for a while. I maintain an alternative jmeter plugin over at http://jmeter.foragerr.net/ that was originally based on this plugin, but has seen a significant rewrites and bug fixes. I would suggest you try that plugin and if you still have an issue, please raise a new issue [here](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues)

**Comment by anujkumar04** [comment]
In the above build file there is a space in the repository url, even after removing the space the issue exists with this plugin.  But after updating to http://jmeter.foragerr.net/ it works. thank you foragerr
